name: Deploy test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/fly-deploy.yml
    with:
      environment: test
      config: fly.test.toml
    secrets: inherit
