name: Deploy dev

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/fly-deploy.yml
    with:
      environment: dev
      config: fly.dev.toml
    secrets: inherit
